# Generated by Django 5.1 on 2024-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('show', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'balances',
                'managed': False,
            },
        ),
    ]
